spring:
  cloud:
    openfeign:
      client:
        config:
          ExchangeRateOpenFeign:
            url: "https://api.apilayer.com"
            connectTimeout: 5000
            readTimeout: 5000

logging:
  level:
    com.youth.javacurrencycalculator.infrastructure.OpenFeignClient: debug

client:
  apikey: ${client.access-key}
