spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  cloud:
    openfeign:
      client:
        config:
          ExchangeRateOpenFeign:
            url: "https://api.apilayer.com"
            connectTimeout: 5000
            readTimeout: 5000

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    com.youth.javacurrencycalculator.infrastructure.OpenFeignClient: debug

client:
  apikey: ${client.access-key}