spring:
  cloud:
    openfeign:
      client:
        config:
          ExchangeRateOpenFeign:
            url: "http://www.apilayer.net/api"
            connectTimeout: 5000
            readTimeout: 5000

logging:
  level:
    com.youth.javacurrencycalculator.infrastructure.OpenFeignClient: debug

client:
  access-key: ${client.access-key}
